#!/usr/bin/env python3
"""
gen_def.py - extract exports from a Windows DLL and emit a .def file
that forwards every export to a renamed copy of the same DLL.

Usage:
    python gen_def.py <original.dll> <forward_target> [output.def]

Example:
    python gen_def.py "C:\\path\\to\\iGP11.Direct3D11.dll" iGP11_Direct3D11_real src/proxy.def

The <forward_target> is the renamed original DLL's basename without the
.dll extension. Constraints:

    - It MUST differ from the source DLL basename (otherwise the forwarder
      loops back into the proxy itself).
    - It MUST NOT contain dots. Windows' loader splits forwarder strings
      on the first dot, so dots in the target name break resolution at
      runtime (ERROR_PROC_NOT_FOUND on every call).

Each export `Foo` becomes:
    Foo = iGP11_Direct3D11_real.Foo @<ordinal>

This script has no external dependencies - it parses PE format directly.
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path


# --- Minimal PE export-table parser ---------------------------------------- #

def _u16(buf: bytes, off: int) -> int:
    return struct.unpack_from("<H", buf, off)[0]


def _u32(buf: bytes, off: int) -> int:
    return struct.unpack_from("<I", buf, off)[0]


def _cstr(buf: bytes, off: int) -> str:
    end = buf.index(b"\x00", off)
    return buf[off:end].decode("ascii", errors="replace")


class Section:
    __slots__ = ("name", "vstart", "vsize", "rstart", "rsize")

    def __init__(self, name, vstart, vsize, rstart, rsize):
        self.name = name
        self.vstart = vstart
        self.vsize = vsize
        self.rstart = rstart
        self.rsize = rsize


def _rva_to_off(sections, rva):
    for s in sections:
        if s.vstart <= rva < s.vstart + max(s.vsize, s.rsize):
            return s.rstart + (rva - s.vstart)
    raise ValueError(f"RVA 0x{rva:08x} not in any section")


def parse_exports(path: Path):
    data = path.read_bytes()
    if data[:2] != b"MZ":
        raise ValueError("not a PE file (no MZ signature)")
    pe_off = _u32(data, 0x3C)
    if data[pe_off:pe_off + 4] != b"PE\x00\x00":
        raise ValueError("not a PE file (no PE signature)")

    machine = _u16(data, pe_off + 4)
    num_sections = _u16(data, pe_off + 6)
    sizeof_optional = _u16(data, pe_off + 20)

    opt_off = pe_off + 24
    magic = _u16(data, opt_off)
    if magic == 0x10B:
        is_64 = False
        data_dir_off = opt_off + 96
    elif magic == 0x20B:
        is_64 = True
        data_dir_off = opt_off + 112
    else:
        raise ValueError(f"unknown PE optional magic: 0x{magic:x}")

    export_rva = _u32(data, data_dir_off + 0)
    export_size = _u32(data, data_dir_off + 4)

    sections_off = opt_off + sizeof_optional
    sections = []
    for i in range(num_sections):
        s = sections_off + i * 40
        sections.append(Section(
            name=_cstr(data, s),
            vsize=_u32(data, s + 8),
            vstart=_u32(data, s + 12),
            rsize=_u32(data, s + 16),
            rstart=_u32(data, s + 20),
        ))

    if export_rva == 0:
        return [], machine, is_64

    exp_off = _rva_to_off(sections, export_rva)
    base_ord = _u32(data, exp_off + 16)
    num_funcs = _u32(data, exp_off + 20)
    num_names = _u32(data, exp_off + 24)
    addr_funcs_rva = _u32(data, exp_off + 28)
    addr_names_rva = _u32(data, exp_off + 32)
    addr_ords_rva = _u32(data, exp_off + 36)

    funcs_off = _rva_to_off(sections, addr_funcs_rva)
    names_off = _rva_to_off(sections, addr_names_rva)
    ords_off = _rva_to_off(sections, addr_ords_rva)

    name_for_index = {}
    for i in range(num_names):
        name_rva = _u32(data, names_off + i * 4)
        name = _cstr(data, _rva_to_off(sections, name_rva))
        idx = _u16(data, ords_off + i * 2)
        name_for_index[idx] = name

    exports = []
    for i in range(num_funcs):
        func_rva = _u32(data, funcs_off + i * 4)
        if func_rva == 0:
            continue  # empty slot
        ordinal = base_ord + i
        name = name_for_index.get(i)
        is_forwarder = export_rva <= func_rva < export_rva + export_size
        forwarder = None
        if is_forwarder:
            forwarder = _cstr(data, _rva_to_off(sections, func_rva))
        exports.append({
            "ordinal": ordinal,
            "name": name,
            "is_forwarder": is_forwarder,
            "forwarder": forwarder,
        })
    return exports, machine, is_64


# --- .def emitter ---------------------------------------------------------- #

MACHINE = {
    0x014C: "x86",
    0x8664: "x64",
    0xAA64: "arm64",
}


def emit_def(exports, target: str, source: str, machine: int, is_64: bool) -> str:
    arch = MACHINE.get(machine, f"0x{machine:04x}")
    lines = [
        f"; Auto-generated by gen_def.py",
        f"; Source : {source}",
        f"; Target : {target}.dll",
        f"; Arch   : {arch}, exports: {len(exports)}",
        "",
        "EXPORTS",
    ]

    for e in exports:
        ordinal = e["ordinal"]
        name = e["name"]
        if name:
            # Named export: forward to target.<name> at the same ordinal.
            lines.append(f"    {name} = {target}.{name} @{ordinal}")
        else:
            # Ordinal-only export: forward by ordinal as a NONAME export.
            lines.append(f"    proxychain_ord_{ordinal} = {target}.#{ordinal} @{ordinal} NONAME")

    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) < 3:
        print(__doc__, file=sys.stderr)
        return 1

    src = Path(argv[1])
    target = argv[2]
    out = Path(argv[3]) if len(argv) > 3 else None

    if target.lower().endswith(".dll"):
        target = target[:-4]

    if not src.is_file():
        print(f"error: {src} not found", file=sys.stderr)
        return 1

    # Catch the most common mistake: forwarding the proxy to its own name.
    src_base = src.stem  # filename without extension
    if src_base.lower() == target.lower():
        print(
            f"error: forward target ('{target}') must differ from the source "
            f"DLL basename ('{src_base}'), otherwise the forwarder will loop "
            f"back into the proxy itself.\n"
            f"hint: pick something like '{src_base.replace('.', '_')}_real' "
            f"and rename the original DLL to that .dll when installing.",
            file=sys.stderr,
        )
        return 2

    # Forwarder strings have the form "<dll>.<func>" and Windows splits on
    # the FIRST dot, not the last. So a target containing dots will be
    # mis-parsed at runtime ("ERROR_PROC_NOT_FOUND" on every export).
    if "." in target:
        print(
            f"error: forward target ('{target}') contains a dot. Windows' "
            f"loader splits forwarder strings on the first dot, so this "
            f"target name will not resolve at runtime.\n"
            f"hint: replace dots with underscores, e.g. '{target.replace('.', '_')}'.",
            file=sys.stderr,
        )
        return 2

    try:
        exports, machine, is_64 = parse_exports(src)
    except Exception as e:
        print(f"error parsing {src}: {e}", file=sys.stderr)
        return 1

    if not exports:
        print(f"warning: no exports found in {src}", file=sys.stderr)

    text = emit_def(exports, target, str(src), machine, is_64)

    if out is None:
        sys.stdout.write(text)
    else:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out} ({len(exports)} exports, "
              f"target='{target}.dll', arch={MACHINE.get(machine, machine)})",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
